---
# tasks file for dockerfile
- name: create distrib dir on remote host
  file:
    path: /tmp/distrib/docker
    state: directory

- name: copy nedeed files on remote host
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: '/home/esm/docker/b7-summary/docker/dockerfile', dest: '/tmp/distrib/docker/' }
    - { src: '/home/esm/docker/b7-summary/distrib/DEVOPS-praktikum_Docker/web.py', dest: '/tmp/distrib/' }
    - { src: '/home/esm/docker/b7-summary/distrib/DEVOPS-praktikum_Docker/web.conf', dest: '/tmp/distrib/' }

- name: edit web.conf
  lineinfile:
    dest: "/tmp/distrib/web.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^db_host', line: 'db_host = ''localhost''' }
    - { regexp: '^db_user', line: 'db_user = ''{{ db_user }}''' }
    - { regexp: '^db_password', line: 'db_password = ''{{ db_pass }}''' }
    - { regexp: '^db_name', line: 'db_name = ''{{ db_name }}''' }
