---
# tasks file for docker
- name: install docker
  apt:
    pkg: 
      - docker.io
      - docker  
    state: present
    update_cache: true

- name: starting docker service
  service:
    name: docker
    state: started

- name: install python-pip for using ansible docker module
  apt:
    name: python3-pip
    state: present

- name: install docker SDK for python
  pip:
    name: docker  

