---
- name: installing&configuring docker and postgresql using roles
  hosts: b7_summ
  gather_facts: true
  become: true
  become_user: "root"
  become_method: "sudo"

  roles:
    - role: "/home/esm/docker/b7-summary/ansible/roles/docker"
